# 修复 libbson 构建问题的脚本
# 在 add_subdirectory(libbson) 之前调用

# 检查 mongo-c-driver common 库
if(EXISTS "${mongo-c-driver_SOURCE_DIR}/src/common/src")
    message(STATUS "Found mongo-c-driver common library at: ${mongo-c-driver_SOURCE_DIR}/src/common/src")
    
    # 生成 common-config.h 文件（如果模板存在）
    if(EXISTS "${mongo-c-driver_SOURCE_DIR}/src/common/src/common-config.h.in")
        # 设置 MONGOC_ENABLE_DEBUG_ASSERTIONS（默认关闭）
        if(NOT DEFINED MONGOC_ENABLE_DEBUG_ASSERTIONS)
            set(MONGOC_ENABLE_DEBUG_ASSERTIONS 0)
        endif()
        if(ENABLE_DEBUG_ASSERTIONS)
            set(MONGOC_ENABLE_DEBUG_ASSERTIONS 1)
        endif()
        
        # 确保构建目录存在
        file(MAKE_DIRECTORY "${mongo-c-driver_BINARY_DIR}/src/common/src")
        
        # 配置 common-config.h 文件
        configure_file(
            "${mongo-c-driver_SOURCE_DIR}/src/common/src/common-config.h.in"
            "${mongo-c-driver_BINARY_DIR}/src/common/src/common-config.h"
            @ONLY
        )
        message(STATUS "Generated common-config.h at: ${mongo-c-driver_BINARY_DIR}/src/common/src/common-config.h")
    endif()
else()
    message(WARNING "mongo-c-driver common library not found at: ${mongo-c-driver_SOURCE_DIR}/src/common/src")
    message(STATUS "Creating fallback common source directory...")
    file(MAKE_DIRECTORY "${mongo-c-driver_SOURCE_DIR}/src/common/src")
    
    # 创建一个空的 .c 文件，避免 GLOB 找不到文件时的警告
    file(WRITE "${mongo-c-driver_SOURCE_DIR}/src/common/src/.gitkeep" "")
endif()

# 创建 packageConfigVersion.cmake.in 文件（如果不存在）
if(NOT EXISTS "${mongo-c-driver_SOURCE_DIR}/build/cmake/packageConfigVersion.cmake.in")
    message(STATUS "Creating packageConfigVersion.cmake.in template...")
    file(MAKE_DIRECTORY "${mongo-c-driver_SOURCE_DIR}/build/cmake")
    file(WRITE "${mongo-c-driver_SOURCE_DIR}/build/cmake/packageConfigVersion.cmake.in"
"# Package version configuration file for @PROJECT_NAME@
# This file is generated by CMake

set(PACKAGE_VERSION \"@PROJECT_VERSION@\")

# Check if the requested PACKAGE_FIND_VERSION is compatible
if(\"${PACKAGE_VERSION}\" VERSION_LESS \"${PACKAGE_FIND_VERSION}\")
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    if (\"${PACKAGE_VERSION}\" VERSION_EQUAL \"${PACKAGE_FIND_VERSION}\")
        set(PACKAGE_VERSION_EXACT TRUE)
    endif()
endif()
")
endif()

# 设置一些 libbson 可能需要的变量
if(NOT DEFINED ENABLE_TESTS)
    set(ENABLE_TESTS OFF)
endif()

if(NOT DEFINED ENABLE_MAN_PAGES)
    set(ENABLE_MAN_PAGES OFF)
endif()

if(NOT DEFINED ENABLE_HTML_DOCS)
    set(ENABLE_HTML_DOCS OFF)
endif()

if(NOT DEFINED ENABLE_PIC)
    set(ENABLE_PIC ON)
endif()

# 设置安装目录变量（如果未定义）
if(NOT DEFINED MONGO_C_DRIVER_INSTALL_CMAKEDIR)
    set(MONGO_C_DRIVER_INSTALL_CMAKEDIR "lib/cmake" CACHE STRING "")
endif()

if(NOT DEFINED BSON_INSTALL_INCLUDEDIR)
    set(BSON_INSTALL_INCLUDEDIR "include" CACHE STRING "")
endif()

if(NOT DEFINED CMAKE_INSTALL_LIBDIR)
    set(CMAKE_INSTALL_LIBDIR "lib" CACHE STRING "")
endif()

if(NOT DEFINED CMAKE_INSTALL_BINDIR)
    set(CMAKE_INSTALL_BINDIR "bin" CACHE STRING "")
endif()

# 创建占位符导出目标，避免 install(EXPORT mongo-platform-targets) 失败
# 创建一个空的接口库并导出它
# 注意：BSON_INSTALL_CMAKEDIR 可能在 libbson 的 CMakeLists.txt 中定义，
# 所以我们需要使用一个默认值或者等待 libbson 定义它
# 但为了在 add_subdirectory 之前创建导出，我们使用默认值
set(_BSON_CMAKEDIR "${MONGO_C_DRIVER_INSTALL_CMAKEDIR}/bson-${PROJECT_VERSION}")
if(NOT DEFINED BSON_INSTALL_CMAKEDIR)
    set(BSON_INSTALL_CMAKEDIR "${_BSON_CMAKEDIR}" CACHE STRING "")
endif()

if(NOT TARGET _mongo_platform_placeholder)
    add_library(_mongo_platform_placeholder INTERFACE)
    # 先安装目标并创建导出集，这样 libbson 的 install(EXPORT) 就能找到它
    # 注意：FILE 参数不能用于 install(TARGETS ... EXPORT ...)，它用于 install(EXPORT ...)
    install(TARGETS _mongo_platform_placeholder
        EXPORT mongo-platform-targets
    )
    # 单独安装导出文件
    install(EXPORT mongo-platform-targets
        FILE 00-mongo-platform-targets.cmake
        DESTINATION "${BSON_INSTALL_CMAKEDIR}"
    )
    message(STATUS "Created placeholder export mongo-platform-targets at ${BSON_INSTALL_CMAKEDIR}")
endif()
